name: Deploy to AWS

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      BASTION_PUBLIC_KEY: ${{ secrets.BASTION_PUBLIC_KEY }}
      EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}
      IMAGE_TAG: latest
      AWS_REGION: eu-central-1
      AWS_ROLE: ${{ secrets.AWS_ROLE }} 
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} 
      ECR_REPOSITORY: porsche_ecr

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff linter
        run: ruff app/

      - name: Check if app.py was modified
        id: file_check
        run: |
          # Dohvati promjene u commitu
          git fetch origin main --depth=1
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q "^app/app.py$"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Amazon ECR
        if: steps.file_check.outputs.changed == 'true'
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        if: steps.file_check.outputs.changed == 'true'
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app

      - name: Push Docker image to ECR
        if: steps.file_check.outputs.changed == 'true'
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Run Terraform
        if: steps.file_check.outputs.changed == 'true'
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="bastion_public_key=$BASTION_PUBLIC_KEY" \
            -var="ec2_public_key=$EC2_PUBLIC_KEY"
