name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      BASTION_PUBLIC_KEY: ${{ secrets.BASTION_PUBLIC_KEY }}
      EC2_PUBLIC_KEY: ${{ secrets.EC2_PUBLIC_KEY }}
      IMAGE_TAG: ${{ github.sha }}
      AWS_REGION: eu-central-1
      AWS_ROLE: ${{ secrets.AWS_ROLE }} 
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} 
      ECR_REPOSITORY: porsche_ecr

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHubActionsSession

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG ./app
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      - name: Run Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="bastion_public_key=$BASTION_PUBLIC_KEY" \
            -var="ec2_public_key=$EC2_PUBLIC_KEY"
